--DROPA A TABELA SE EXISTIR
DROP TABLE IF EXISTS TB_HEROES;

--- CRIA A TABELA
CREATE TABLE TB_HEROES(
  ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  NAME TEXT NOT NULL ,
  POWER TEXT NOT NULL
);

--INSERE REGISTRO
INSERT INTO TB_HEROES(NAME, POWER)
VALUES ('NAME 1', 'POWER 1'), ('NAME 2', 'POWER 2'), ('NAME 3', 'POWER 3');

--SELECIONA OS REGISTROS
SELECT * FROM TB_HEROES;

--APAGA REGISTRO
DELETE FROM TB_HEROES WHERE ID = 1;

--SELECIONA OS REGISTROS
SELECT * FROM TB_HEROES;

--ATUALIZA REGISTRO

UPDATE TB_HEROES
SET NAME = 'FULL NAME 1', POWER = 'FULL POWER 1'
WHERE ID = 2;

--SELECIONA OS REGISTROS
SELECT * FROM TB_HEROES;